# Generated by Django 6.0.4 on 2026-05-04 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'medidas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('contacto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('despachador', 'Despachador')], max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('pasillo', models.CharField(max_length=10)),
                ('estante', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('estado_ocupacion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ubicaciones',
                'unique_together': {('pasillo', 'estante', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField(default=1)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('categoria', models.CharField(choices=[('electronica', 'Electrónica'), ('textil', 'Textil'), ('alimento', 'Alimento'), ('herramienta', 'Herramienta'), ('quimico', 'Químico'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('es_fragil', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('clasificada', 'Clasificada'), ('en_transito', 'En tránsito'), ('almacenada', 'Almacenada'), ('despachada', 'Despachada')], default='pendiente', max_length=20)),
                ('hora_llegada', models.DateTimeField(auto_now_add=True)),
                ('id_medida', models.ForeignKey(db_column='id_medida', on_delete=django.db.models.deletion.PROTECT, to='clasificacion.medida')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.PROTECT, to='clasificacion.proveedor')),
                ('id_ubicacion', models.ForeignKey(blank=True, db_column='id_ubicacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clasificacion.ubicacion')),
            ],
            options={
                'db_table': 'caja',
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimientos',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.CASCADE, to='clasificacion.caja')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='clasificacion.usuario')),
            ],
            options={
                'db_table': 'historial_movimientos',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.AutoField(primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=200)),
                ('transporte_placa', models.CharField(max_length=20)),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.CASCADE, to='clasificacion.caja')),
                ('id_usuario_despacho', models.ForeignKey(db_column='id_usuario_despacho', on_delete=django.db.models.deletion.PROTECT, to='clasificacion.usuario')),
            ],
            options={
                'db_table': 'despacho',
            },
        ),
    ]
