# Generated by Django 6.0.4 on 2026-05-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCarro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('destino_x', models.IntegerField(default=0)),
                ('destino_y', models.IntegerField(default=0)),
                ('ruta', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('esperando', 'Esperando'), ('moviendo', 'Moviendo'), ('llego', 'Llegó')], default='esperando', max_length=20)),
                ('caja_id', models.CharField(blank=True, max_length=20, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estado_carro',
            },
        ),
    ]
