# Generated by Django 6.0.4 on 2026-05-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0002_estadocarro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='capacidad_peso_kg',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='permite_fragil',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='permite_quimico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='prioridad_categoria',
            field=models.CharField(choices=[('sin_preferencia', 'Sin preferencia'), ('electronica', 'Electrónica'), ('textil', 'Textil'), ('alimento', 'Alimento'), ('herramienta', 'Herramienta'), ('quimico', 'Químico'), ('otro', 'Otro')], default='sin_preferencia', max_length=20),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipo_estante',
            field=models.CharField(choices=[('general', 'General'), ('pesado', 'Carga pesada'), ('fragil', 'Frágil'), ('quimico', 'Químico'), ('refrigerado', 'Refrigerado')], default='general', max_length=20),
        ),
    ]
