# Generated by Django 6.0.4 on 2026-05-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0003_ubicacion_capacidad_peso_kg_ubicacion_permite_fragil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocarro',
            name='parada_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadocarro',
            name='paradas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
