# Generated by Django 6.0.4 on 2026-05-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0004_estadocarro_multiparada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(default='📦', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='caja',
            name='categoria',
            field=models.CharField(default='otro', max_length=30),
        ),
    ]
