# Generated by Django 6.0.4 on 2026-05-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0006_seed_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Carro Principal', max_length=50)),
                ('largo_cm', models.DecimalField(decimal_places=1, default=100, max_digits=8)),
                ('ancho_cm', models.DecimalField(decimal_places=1, default=80, max_digits=8)),
                ('alto_cm', models.DecimalField(decimal_places=1, default=120, max_digits=8)),
                ('peso_maximo_kg', models.DecimalField(decimal_places=2, default=150, max_digits=8)),
                ('max_paradas', models.IntegerField(default=10)),
                ('pos_base_x', models.IntegerField(default=0)),
                ('pos_base_y', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'config_carro',
            },
        ),
        migrations.AlterField(
            model_name='estadocarro',
            name='estado',
            field=models.CharField(choices=[('esperando', 'Esperando'), ('moviendo', 'Moviendo'), ('llego', 'Llegó'), ('regresando', 'Regresando a base')], default='esperando', max_length=20),
        ),
    ]
