# Generated by Django 6.0.4 on 2026-06-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0008_destino_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocarro',
            name='motor_der_vel',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='estadocarro',
            name='motor_izq_vel',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='estadocarro',
            name='sensor_obstaculo_frontal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadocarro',
            name='sensor_obstaculo_trasero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadocarro',
            name='sensor_opt_der_ext',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadocarro',
            name='sensor_opt_der_int',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadocarro',
            name='sensor_opt_izq_ext',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadocarro',
            name='sensor_opt_izq_int',
            field=models.BooleanField(default=False),
        ),
    ]
