# Generated by Django 6.0.4 on 2026-06-21 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_data(apps, schema_editor):
    from django.contrib.auth.models import User
    Vehiculo = apps.get_model('clasificacion', 'Vehiculo')
    Destino = apps.get_model('clasificacion', 'Destino')

    # Create admin
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', 'Montescoli3')

    # Create controlador
    if not User.objects.filter(username='controlador').exists():
        User.objects.create_user('controlador', 'controlador@example.com', 'Montescoli3')

    # Create vehicles
    Vehiculo.objects.get_or_create(placa='AAA-123', defaults={'marca': 'Volvo FMX', 'capacidad_kg': 12000})
    Vehiculo.objects.get_or_create(placa='BBB-456', defaults={'marca': 'Hyundai HD78', 'capacidad_kg': 4500})

    # Create destinations
    Destino.objects.get_or_create(nombre='Sede Principal Norte', defaults={'direccion': 'Av. Industrial 550, Lima'})
    Destino.objects.get_or_create(nombre='Centro de Distribución Sur', defaults={'direccion': 'Panamericana Sur Km 24, Lurín'})


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0009_estadocarro_motor_der_vel_estadocarro_motor_izq_vel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDespacho',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('cajas_ids', models.JSONField(default=list)),
                ('destino', models.CharField(max_length=200)),
                ('transporte_placa', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('operador_responsable', models.ForeignKey(db_column='id_operador_responsable', on_delete=django.db.models.deletion.PROTECT, to='clasificacion.usuario')),
                ('usuario_solicita', models.ForeignKey(db_column='id_usuario_solicita', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitud_despacho',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.RunPython(seed_data),
    ]

