# Generated by Django 6.0.4 on 2026-06-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0010_solicituddespacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocarro',
            name='bateria_pct',
            field=models.IntegerField(default=100),
        ),
    ]
