# Generated by Django 6.0.4 on 2026-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0011_estadocarro_bateria_pct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='casillero',
            field=models.IntegerField(choices=[(1, 'Casillero 1'), (2, 'Casillero 2')], default=1),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='lado',
            field=models.CharField(choices=[('adelante', 'Adelante'), ('posterior', 'Posterior')], default='adelante', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('pasillo', 'estante', 'nivel', 'lado', 'casillero')},
        ),
    ]
