# Generated by Django 6.0.4 on 2026-06-28 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0012_alter_ubicacion_unique_together_ubicacion_casillero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcarro',
            name='pos_base_x',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id_planilla', models.AutoField(primary_key=True, serialize=False)),
                ('cajas_ids', models.JSONField(default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planilla',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
