from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def seed_products(apps, schema_editor):
    Caja = apps.get_model('clasificacion', 'Caja'); Producto = apps.get_model('clasificacion', 'Producto')
    for index, values in enumerate(Caja.objects.values('producto', 'categoria').distinct(), start=1):
        product, _ = Producto.objects.get_or_create(nombre=values['producto'], defaults={'sku': f'PRD-{index:05d}', 'categoria': values['categoria'] or 'otro'})
        Caja.objects.filter(producto=values['producto']).update(producto_ref=product)

class Migration(migrations.Migration):
    dependencies = [('clasificacion', '0016_seed_warehouse_specializations'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Producto', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('sku', models.CharField(max_length=40, unique=True)), ('nombre', models.CharField(max_length=150)), ('categoria', models.CharField(default='otro', max_length=30)), ('codigo_barras', models.CharField(blank=True, max_length=64, null=True, unique=True)), ('unidad', models.CharField(default='unidad', max_length=30)), ('activo', models.BooleanField(default=True)), ('creado_en', models.DateTimeField(auto_now_add=True))], options={'db_table':'producto','ordering':['nombre']}),
        migrations.AddField(model_name='caja', name='producto_ref', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='clasificacion.producto')),
        migrations.AddField(model_name='caja', name='codigo_barras', field=models.CharField(blank=True, max_length=64, null=True, unique=True)),
        migrations.AddField(model_name='caja', name='lote', field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name='caja', name='fecha_vencimiento', field=models.DateField(blank=True, db_index=True, null=True)),
        migrations.AddField(model_name='despacho', name='cantidad', field=models.PositiveIntegerField(default=1)),
        migrations.CreateModel(name='PoliticaStock', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('producto', models.CharField(max_length=150, unique=True)), ('minimo', models.PositiveIntegerField(default=0)), ('maximo', models.PositiveIntegerField(blank=True, null=True)), ('dias_sin_movimiento', models.PositiveIntegerField(default=30)), ('activa', models.BooleanField(default=True))], options={'db_table': 'politica_stock', 'ordering': ['producto']}),
        migrations.CreateModel(name='MovimientoInventario', fields=[('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)), ('tipo', models.CharField(choices=[('entrada','Entrada'),('salida','Salida'),('reserva','Reserva'),('liberacion','Liberación'),('traslado','Traslado'),('ajuste','Ajuste')], max_length=20)), ('cantidad', models.IntegerField()), ('existencia_anterior', models.PositiveIntegerField()), ('existencia_posterior', models.PositiveIntegerField()), ('motivo', models.CharField(blank=True, max_length=240)), ('referencia', models.CharField(blank=True, max_length=80)), ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)), ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='clasificacion.caja')), ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clasificacion.ubicacion')), ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clasificacion.ubicacion')), ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))], options={'db_table':'movimiento_inventario','ordering':['-fecha','-id_movimiento']}),
        migrations.CreateModel(name='ReservaStock', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('cantidad', models.PositiveIntegerField()), ('estado', models.CharField(choices=[('activa','Activa'),('consumida','Consumida'),('cancelada','Cancelada')], db_index=True, default='activa', max_length=12)), ('destino', models.CharField(blank=True, max_length=200)), ('creada_en', models.DateTimeField(auto_now_add=True)), ('actualizada_en', models.DateTimeField(auto_now=True)), ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clasificacion.caja')), ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL))], options={'db_table':'reserva_stock','ordering':['-creada_en']}),
        migrations.RunPython(seed_products, migrations.RunPython.noop),
    ]
