# Generated by Django 6.0.4 on 2026-07-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0018_suscripcion'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL('DROP TABLE IF EXISTS config_carro'),
                migrations.RunSQL('DROP TABLE IF EXISTS estado_carro'),
            ],
            state_operations=[
                migrations.DeleteModel(name='ConfigCarro'),
                migrations.DeleteModel(name='EstadoCarro'),
            ],
        ),
    ]
