# Generated by Django 6.0.4 on 2026-07-12 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def vincular_usuarios_existentes(apps, schema_editor):
    Usuario = apps.get_model('clasificacion', 'Usuario')
    AuthUser = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    for usuario in Usuario.objects.filter(usuario_auth__isnull=True):
        auth_user = AuthUser.objects.filter(username__iexact=usuario.nombre).first()
        if auth_user:
            usuario.usuario_auth = auth_user
            usuario.save(update_fields=['usuario_auth'])


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0019_remove_agv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_auth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfil_logistico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(vincular_usuarios_existentes, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL('DROP TABLE IF EXISTS vehiculo')],
            state_operations=[migrations.DeleteModel(name='Vehiculo')],
        ),
    ]
