# Generated by Django 6.0.4 on 2026-07-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0020_remove_vehicle_and_link_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre_empresa']},
        ),
    ]
