# Generated by Django 6.0.4 on 2026-07-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0021_order_catalogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, default=1000, max_digits=8)),
            ],
            options={
                'db_table': 'vehiculo',
                'ordering': ['placa'],
            },
        ),
    ]
