# Generated by Django 6.0.4 on 2026-07-13 04:19

from decimal import Decimal

from django.db import migrations, models


def calibrate_warehouse(apps, schema_editor):
    Ubicacion = apps.get_model('clasificacion', 'Ubicacion')
    Caja = apps.get_model('clasificacion', 'Caja')

    zones = {
        ('A', 1): {
            'tipo_estante': 'fragil', 'prioridad_categoria': 'electronica',
            'permite_fragil': True, 'permite_quimico': False,
            'ancho': 55, 'fondo': 60, 'altos': {1: 55, 2: 50, 3: 45},
            'capacidades': {1: 45, 2: 35, 3: 25}, 'distancia': Decimal('4.0'),
        },
        ('A', 2): {
            'tipo_estante': 'pesado', 'prioridad_categoria': 'herramienta',
            'permite_fragil': False, 'permite_quimico': False,
            'ancho': 90, 'fondo': 100, 'altos': {1: 75, 2: 70, 3: 60},
            'capacidades': {1: 250, 2: 180, 3: 100}, 'distancia': Decimal('7.0'),
        },
        ('A', 3): {
            'tipo_estante': 'refrigerado', 'prioridad_categoria': 'alimento',
            'permite_fragil': True, 'permite_quimico': False,
            'ancho': 60, 'fondo': 65, 'altos': {1: 55, 2: 50, 3: 45},
            'capacidades': {1: 60, 2: 45, 3: 30}, 'distancia': Decimal('10.0'),
        },
        ('B', 1): {
            'tipo_estante': 'quimico', 'prioridad_categoria': 'quimico',
            'permite_fragil': False, 'permite_quimico': True,
            'ancho': 60, 'fondo': 60, 'altos': {1: 60, 2: 55, 3: 50},
            'capacidades': {1: 100, 2: 75, 3: 50}, 'distancia': Decimal('8.0'),
        },
        ('B', 2): {
            'tipo_estante': 'general', 'prioridad_categoria': 'textil',
            'permite_fragil': True, 'permite_quimico': False,
            'ancho': 90, 'fondo': 85, 'altos': {1: 70, 2: 65, 3: 55},
            'capacidades': {1: 90, 2: 65, 3: 45}, 'distancia': Decimal('11.0'),
        },
        ('B', 3): {
            'tipo_estante': 'general', 'prioridad_categoria': 'otro',
            'permite_fragil': True, 'permite_quimico': False,
            'ancho': 80, 'fondo': 80, 'altos': {1: 65, 2: 60, 3: 50},
            'capacidades': {1: 80, 2: 60, 3: 40}, 'distancia': Decimal('14.0'),
        },
    }

    for location in Ubicacion.objects.all():
        zone = zones.get((location.pasillo.upper(), location.estante))
        if not zone:
            continue
        location.tipo_estante = zone['tipo_estante']
        location.prioridad_categoria = zone['prioridad_categoria']
        location.permite_fragil = zone['permite_fragil']
        location.permite_quimico = zone['permite_quimico']
        location.ancho_util_cm = Decimal(str(zone['ancho']))
        location.fondo_util_cm = Decimal(str(zone['fondo']))
        location.alto_util_cm = Decimal(str(zone['altos'].get(location.nivel, 50)))
        location.capacidad_peso_kg = Decimal(str(zone['capacidades'].get(location.nivel, 40)))
        side_extra = Decimal('0.8') if location.lado == 'posterior' else Decimal('0')
        locker_extra = Decimal('0.3') if location.casillero == 2 else Decimal('0')
        location.distancia_salida_m = zone['distancia'] + side_extra + locker_extra
        location.activo = True
        location.save(update_fields=[
            'tipo_estante', 'prioridad_categoria', 'permite_fragil', 'permite_quimico',
            'ancho_util_cm', 'fondo_util_cm', 'alto_util_cm', 'capacidad_peso_kg',
            'distancia_salida_m', 'activo',
        ])

    Caja.objects.filter(
        categoria='alimento', id_ubicacion__tipo_estante='refrigerado',
    ).update(requiere_refrigeracion=True)


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0023_despachooperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='requiere_refrigeracion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='alto_util_cm',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=7),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ancho_util_cm',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=7),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='distancia_salida_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='fondo_util_cm',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=7),
        ),
        migrations.RunPython(calibrate_warehouse, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(
                condition=models.Q(capacidad_peso_kg__gt=0),
                name='ubicacion_capacidad_peso_positiva',
            ),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(ancho_util_cm__gt=0)
                    & models.Q(fondo_util_cm__gt=0)
                    & models.Q(alto_util_cm__gt=0)
                ),
                name='ubicacion_dimensiones_positivas',
            ),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(
                condition=models.Q(distancia_salida_m__gte=0),
                name='ubicacion_distancia_no_negativa',
            ),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(
                condition=models.Q(estante__gte=1) & models.Q(nivel__gte=1),
                name='ubicacion_indices_positivos',
            ),
        ),
    ]
