# Generated by Django 6.0.4 on 2026-07-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0025_slotting_safety_capabilities'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='caja_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.CheckConstraint(condition=models.Q(('peso_kg__gt', 0)), name='caja_peso_positivo'),
        ),
        migrations.AddConstraint(
            model_name='medida',
            constraint=models.CheckConstraint(condition=models.Q(('largo__gt', 0), ('ancho__gt', 0), ('alto__gt', 0), ('volumen__gt', 0)), name='medida_dimensiones_positivas'),
        ),
    ]
