# Generated by Django 6.0.4 on 2026-07-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0026_warehouse_data_integrity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='caja',
            name='caja_cantidad_positiva',
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0), models.Q(('cantidad', 0), ('estado', 'despachada')), _connector='OR'), name='caja_cantidad_positiva'),
        ),
    ]
